# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PayTypeDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_PayTypeDetail(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 200)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 450, 61))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 35, 35))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/System Tables.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lblPayType = QtWidgets.QLabel(self.frame)
        self.lblPayType.setGeometry(QtCore.QRect(50, 10, 160, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblPayType.setFont(font)
        self.lblPayType.setObjectName("lblPayType")
        self.btnSave = QtWidgets.QPushButton(self.frame)
        self.btnSave.setGeometry(QtCore.QRect(260, 10, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("background-color: rgb(240, 80, 128);\n"
"color: rgb(255, 255, 255);")
        self.btnSave.setObjectName("btnSave")
        self.pushButtonClose = QtWidgets.QPushButton(self.frame)
        self.pushButtonClose.setGeometry(QtCore.QRect(360, 10, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setStyleSheet("background-color: rgb(243, 79, 28);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 60, 450, 140))
        self.frame_2.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txtCode = QtWidgets.QTextEdit(self.frame_2)
        self.txtCode.setGeometry(QtCore.QRect(160, 10, 281, 31))
        self.txtCode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtCode.setObjectName("txtCode")
        self.txtPayType = QtWidgets.QTextEdit(self.frame_2)
        self.txtPayType.setGeometry(QtCore.QRect(160, 50, 281, 31))
        self.txtPayType.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtPayType.setObjectName("txtPayType")
        self.cboAccount = QtWidgets.QComboBox(self.frame_2)
        self.cboAccount.setGeometry(QtCore.QRect(160, 90, 281, 31))
        self.cboAccount.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cboAccount.setObjectName("cboAccount")
        self.lblCode = QtWidgets.QLabel(self.frame_2)
        self.lblCode.setGeometry(QtCore.QRect(10, 10, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblCode.setFont(font)
        self.lblCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCode.setObjectName("lblCode")
        self.lblPayType_2 = QtWidgets.QLabel(self.frame_2)
        self.lblPayType_2.setGeometry(QtCore.QRect(10, 50, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblPayType_2.setFont(font)
        self.lblPayType_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPayType_2.setObjectName("lblPayType_2")
        self.lblAccount = QtWidgets.QLabel(self.frame_2)
        self.lblAccount.setGeometry(QtCore.QRect(10, 90, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblAccount.setFont(font)
        self.lblAccount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAccount.setObjectName("lblAccount")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblPayType.setText(_translate("Form", "Pay Type Detail"))
        self.btnSave.setText(_translate("Form", "Enter - Save"))
        self.pushButtonClose.setText(_translate("Form", "Esc - Close"))
        self.lblCode.setText(_translate("Form", "Code:"))
        self.lblPayType_2.setText(_translate("Form", "Pay Type:"))
        self.lblAccount.setText(_translate("Form", "Account:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UI_PayTypeDetail()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
