

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 353)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 450, 61))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 35, 35))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/User.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lblTaxDetail = QtWidgets.QLabel(self.frame)
        self.lblTaxDetail.setGeometry(QtCore.QRect(50, 10, 160, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblTaxDetail.setFont(font)
        self.lblTaxDetail.setObjectName("lblTaxDetail")
        self.btnSave = QtWidgets.QPushButton(self.frame)
        self.btnSave.setGeometry(QtCore.QRect(260, 10, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("background-color: rgb(240, 80, 128);\n"
"color: rgb(255, 255, 255);")
        self.btnSave.setObjectName("btnSave")
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setGeometry(QtCore.QRect(360, 10, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("background-color: rgb(243, 79, 28);\n"
"color: rgb(255, 255, 255);")
        self.btnClose.setObjectName("btnClose")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 60, 450, 321))
        self.frame_2.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lblUnit = QtWidgets.QLabel(self.frame_2)
        self.lblUnit.setGeometry(QtCore.QRect(10, 15, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblUnit.setFont(font)
        self.lblUnit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUnit.setObjectName("lblUnit")
        self.comboBoxForm = QtWidgets.QComboBox(self.frame_2)
        self.comboBoxForm.setGeometry(QtCore.QRect(50, 10, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.comboBoxForm.setFont(font)
        self.comboBoxForm.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxForm.setObjectName("comboBoxForm")
        self.checkBoxCanDelete = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanDelete.setGeometry(QtCore.QRect(30, 50, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanDelete.setFont(font)
        self.checkBoxCanDelete.setObjectName("checkBoxCanDelete")
        self.checkBoxCanAdd = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanAdd.setGeometry(QtCore.QRect(30, 80, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanAdd.setFont(font)
        self.checkBoxCanAdd.setObjectName("checkBoxCanAdd")
        self.checkBoxCanLock = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanLock.setGeometry(QtCore.QRect(30, 110, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanLock.setFont(font)
        self.checkBoxCanLock.setObjectName("checkBoxCanLock")
        self.checkBoxCanUnlock = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanUnlock.setGeometry(QtCore.QRect(30, 140, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanUnlock.setFont(font)
        self.checkBoxCanUnlock.setObjectName("checkBoxCanUnlock")
        self.checkBoxCanPrint = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanPrint.setGeometry(QtCore.QRect(30, 170, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanPrint.setFont(font)
        self.checkBoxCanPrint.setObjectName("checkBoxCanPrint")
        self.checkBoxCanPreview = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanPreview.setGeometry(QtCore.QRect(30, 200, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanPreview.setFont(font)
        self.checkBoxCanPreview.setObjectName("checkBoxCanPreview")
        self.checkBoxCanEdit = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanEdit.setGeometry(QtCore.QRect(30, 230, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanEdit.setFont(font)
        self.checkBoxCanEdit.setObjectName("checkBoxCanEdit")
        self.checkBoxCanTender = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanTender.setGeometry(QtCore.QRect(30, 260, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanTender.setFont(font)
        self.checkBoxCanTender.setObjectName("checkBoxCanTender")
        self.checkBoxCanReturn = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanReturn.setGeometry(QtCore.QRect(210, 170, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanReturn.setFont(font)
        self.checkBoxCanReturn.setObjectName("checkBoxCanReturn")
        self.checkBoxCanView = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanView.setGeometry(QtCore.QRect(210, 80, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanView.setFont(font)
        self.checkBoxCanView.setObjectName("checkBoxCanView")
        self.checkBoxCanCancel = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanCancel.setGeometry(QtCore.QRect(210, 140, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanCancel.setFont(font)
        self.checkBoxCanCancel.setObjectName("checkBoxCanCancel")
        self.checkBoxCanSplit = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanSplit.setGeometry(QtCore.QRect(210, 110, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanSplit.setFont(font)
        self.checkBoxCanSplit.setObjectName("checkBoxCanSplit")
        self.checkBoxCanDiscount = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxCanDiscount.setGeometry(QtCore.QRect(210, 50, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBoxCanDiscount.setFont(font)
        self.checkBoxCanDiscount.setObjectName("checkBoxCanDiscount")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblTaxDetail.setText(_translate("Form", "User Form Detail"))
        self.btnSave.setText(_translate("Form", "Save"))
        self.btnClose.setText(_translate("Form", "Close"))
        self.lblUnit.setText(_translate("Form", "Form:"))
        self.checkBoxCanDelete.setText(_translate("Form", "Can Delete"))
        self.checkBoxCanAdd.setText(_translate("Form", "Can Add"))
        self.checkBoxCanLock.setText(_translate("Form", "Can Lock"))
        self.checkBoxCanUnlock.setText(_translate("Form", "Can Unlock"))
        self.checkBoxCanPrint.setText(_translate("Form", "Can Print"))
        self.checkBoxCanPreview.setText(_translate("Form", "Can Preview"))
        self.checkBoxCanEdit.setText(_translate("Form", "Can Edit"))
        self.checkBoxCanTender.setText(_translate("Form", "Can Tender"))
        self.checkBoxCanReturn.setText(_translate("Form", "Can Return"))
        self.checkBoxCanView.setText(_translate("Form", "Can View"))
        self.checkBoxCanCancel.setText(_translate("Form", "Can Cancel"))
        self.checkBoxCanSplit.setText(_translate("Form", "Can Split"))
        self.checkBoxCanDiscount.setText(_translate("Form", "Can Discount"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())