# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaxDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 250)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 450, 61))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 35, 35))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/System Tables.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lblTaxDetail = QtWidgets.QLabel(self.frame)
        self.lblTaxDetail.setGeometry(QtCore.QRect(50, 10, 160, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblTaxDetail.setFont(font)
        self.lblTaxDetail.setObjectName("lblTaxDetail")
        self.btnSave = QtWidgets.QPushButton(self.frame)
        self.btnSave.setGeometry(QtCore.QRect(260, 10, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("background-color: rgb(240, 80, 128);\n"
"color: rgb(255, 255, 255);")
        self.btnSave.setObjectName("btnSave")
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setGeometry(QtCore.QRect(360, 10, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("background-color: rgb(243, 79, 28);\n"
"color: rgb(255, 255, 255);")
        self.btnClose.setObjectName("btnClose")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 60, 450, 190))
        self.frame_2.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txtCode = QtWidgets.QTextEdit(self.frame_2)
        self.txtCode.setGeometry(QtCore.QRect(140, 10, 300, 31))
        self.txtCode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtCode.setObjectName("txtCode")
        self.txtTax = QtWidgets.QTextEdit(self.frame_2)
        self.txtTax.setGeometry(QtCore.QRect(140, 50, 300, 31))
        self.txtTax.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtTax.setObjectName("txtTax")
        self.cboAccount = QtWidgets.QComboBox(self.frame_2)
        self.cboAccount.setGeometry(QtCore.QRect(140, 130, 300, 31))
        self.cboAccount.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.cboAccount.setObjectName("cboAccount")
        self.txtRate = QtWidgets.QTextEdit(self.frame_2)
        self.txtRate.setGeometry(QtCore.QRect(140, 90, 150, 31))
        self.txtRate.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtRate.setObjectName("txtRate")
        self.lblCode = QtWidgets.QLabel(self.frame_2)
        self.lblCode.setGeometry(QtCore.QRect(10, 10, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblCode.setFont(font)
        self.lblCode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCode.setObjectName("lblCode")
        self.lblTax = QtWidgets.QLabel(self.frame_2)
        self.lblTax.setGeometry(QtCore.QRect(10, 50, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblTax.setFont(font)
        self.lblTax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTax.setObjectName("lblTax")
        self.lblRate = QtWidgets.QLabel(self.frame_2)
        self.lblRate.setGeometry(QtCore.QRect(10, 90, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblRate.setFont(font)
        self.lblRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRate.setObjectName("lblRate")
        self.lblAccount = QtWidgets.QLabel(self.frame_2)
        self.lblAccount.setGeometry(QtCore.QRect(10, 130, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblAccount.setFont(font)
        self.lblAccount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAccount.setObjectName("lblAccount")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblTaxDetail.setText(_translate("Form", "Tax Detail"))
        self.btnSave.setText(_translate("Form", "Enter - Save"))
        self.btnClose.setText(_translate("Form", "Esc - Close"))
        self.lblCode.setText(_translate("Form", "Code:"))
        self.lblTax.setText(_translate("Form", "Tax:"))
        self.lblRate.setText(_translate("Form", "Rate:"))
        self.lblAccount.setText(_translate("Form", "Account:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
