# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItemCategoryDetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_ItemCategoryDetail(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 125)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 500, 61))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 35, 35))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/System Tables.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lblItemCategoryDetail = QtWidgets.QLabel(self.frame)
        self.lblItemCategoryDetail.setGeometry(QtCore.QRect(50, 10, 210, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblItemCategoryDetail.setFont(font)
        self.lblItemCategoryDetail.setObjectName("lblItemCategoryDetail")
        self.btnSave = QtWidgets.QPushButton(self.frame)
        self.btnSave.setGeometry(QtCore.QRect(310, 10, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("background-color: rgb(240, 80, 128);\n"
"color: rgb(255, 255, 255);")
        self.btnSave.setObjectName("btnSave")
        self.btnClose = QtWidgets.QPushButton(self.frame)
        self.btnClose.setGeometry(QtCore.QRect(410, 10, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("background-color: rgb(243, 79, 28);\n"
"color: rgb(255, 255, 255);")
        self.btnClose.setObjectName("btnClose")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 60, 500, 190))
        self.frame_2.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txtCategory = QtWidgets.QTextEdit(self.frame_2)
        self.txtCategory.setGeometry(QtCore.QRect(140, 10, 350, 31))
        self.txtCategory.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtCategory.setObjectName("txtCategory")
        self.lblCategory = QtWidgets.QLabel(self.frame_2)
        self.lblCategory.setGeometry(QtCore.QRect(10, 10, 120, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.lblCategory.setFont(font)
        self.lblCategory.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCategory.setObjectName("lblCategory")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblItemCategoryDetail.setText(_translate("Form", "Item Category Detail"))
        self.btnSave.setText(_translate("Form", "Enter - Save"))
        self.btnClose.setText(_translate("Form", "Esc - Close"))
        self.lblCategory.setText(_translate("Form", "Category:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = UI_ItemCategoryDetail()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
