from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1365, 768)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1366, 60))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 38, 32))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/Item.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.pushButtonClose = QtWidgets.QPushButton(self.frame)
        self.pushButtonClose.setGeometry(QtCore.QRect(1280, 10, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setStyleSheet("background-color: rgb(243, 79, 28);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonClose.setFlat(False)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.pushButtonUnlock = QtWidgets.QPushButton(self.frame)
        self.pushButtonUnlock.setGeometry(QtCore.QRect(1200, 10, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUnlock.setFont(font)
        self.pushButtonUnlock.setAutoFillBackground(False)
        self.pushButtonUnlock.setStyleSheet("background-color: rgb(240, 80, 128);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonUnlock.setObjectName("pushButtonUnlock")
        self.pushButtonLock = QtWidgets.QPushButton(self.frame)
        self.pushButtonLock.setGeometry(QtCore.QRect(1120, 10, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLock.setFont(font)
        self.pushButtonLock.setAutoFillBackground(False)
        self.pushButtonLock.setStyleSheet("background-color: rgb(240, 80, 128);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonLock.setObjectName("pushButtonLock")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 60, 1361, 711))
        self.frame_2.setStyleSheet("background-color: rgb(240,240,240);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1365, 711))
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneralInformation = QtWidgets.QWidget()
        self.tabGeneralInformation.setObjectName("tabGeneralInformation")
        self.frame_5 = QtWidgets.QFrame(self.tabGeneralInformation)
        self.frame_5.setGeometry(QtCore.QRect(-10, 0, 1361, 861))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.textEditItemCode = QtWidgets.QTextEdit(self.frame_5)
        self.textEditItemCode.setGeometry(QtCore.QRect(150, 7, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditItemCode.setFont(font)
        self.textEditItemCode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditItemCode.setObjectName("textEditItemCode")
        self.textEditItemDescription = QtWidgets.QTextEdit(self.frame_5)
        self.textEditItemDescription.setGeometry(QtCore.QRect(150, 73, 401, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditItemDescription.setFont(font)
        self.textEditItemDescription.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditItemDescription.setObjectName("textEditItemDescription")
        self.textEditBarcode = QtWidgets.QTextEdit(self.frame_5)
        self.textEditBarcode.setGeometry(QtCore.QRect(150, 40, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditBarcode.setFont(font)
        self.textEditBarcode.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditBarcode.setObjectName("textEditBarcode")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(30, 43, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_53 = QtWidgets.QLabel(self.frame_5)
        self.label_53.setGeometry(QtCore.QRect(30, 80, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.frame_5)
        self.label_54.setGeometry(QtCore.QRect(30, 210, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.textEditAlias = QtWidgets.QTextEdit(self.frame_5)
        self.textEditAlias.setGeometry(QtCore.QRect(150, 205, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditAlias.setFont(font)
        self.textEditAlias.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditAlias.setObjectName("textEditAlias")
        self.comboBoxCategory = QtWidgets.QComboBox(self.frame_5)
        self.comboBoxCategory.setGeometry(QtCore.QRect(150, 237, 241, 31))
        self.comboBoxCategory.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxCategory.setObjectName("comboBoxCategory")
        self.label_55 = QtWidgets.QLabel(self.frame_5)
        self.label_55.setGeometry(QtCore.QRect(30, 240, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.label_62 = QtWidgets.QLabel(self.frame_5)
        self.label_62.setGeometry(QtCore.QRect(30, 273, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.comboBoxUnit = QtWidgets.QComboBox(self.frame_5)
        self.comboBoxUnit.setGeometry(QtCore.QRect(150, 270, 121, 31))
        self.comboBoxUnit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxUnit.setObjectName("comboBoxUnit")
        self.label_63 = QtWidgets.QLabel(self.frame_5)
        self.label_63.setGeometry(QtCore.QRect(30, 310, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.comboBoxSupplier = QtWidgets.QComboBox(self.frame_5)
        self.comboBoxSupplier.setGeometry(QtCore.QRect(150, 303, 241, 31))
        self.comboBoxSupplier.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxSupplier.setObjectName("comboBoxSupplier")
        self.label_64 = QtWidgets.QLabel(self.frame_5)
        self.label_64.setGeometry(QtCore.QRect(30, 340, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.textEditCost = QtWidgets.QTextEdit(self.frame_5)
        self.textEditCost.setGeometry(QtCore.QRect(150, 336, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditCost.setFont(font)
        self.textEditCost.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditCost.setObjectName("textEditCost")
        self.label_65 = QtWidgets.QLabel(self.frame_5)
        self.label_65.setGeometry(QtCore.QRect(30, 370, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.textEditMarkUp = QtWidgets.QTextEdit(self.frame_5)
        self.textEditMarkUp.setGeometry(QtCore.QRect(150, 368, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditMarkUp.setFont(font)
        self.textEditMarkUp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditMarkUp.setObjectName("textEditMarkUp")
        self.textEditPrice = QtWidgets.QTextEdit(self.frame_5)
        self.textEditPrice.setGeometry(QtCore.QRect(150, 400, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditPrice.setFont(font)
        self.textEditPrice.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditPrice.setObjectName("textEditPrice")
        self.label_66 = QtWidgets.QLabel(self.frame_5)
        self.label_66.setGeometry(QtCore.QRect(30, 403, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.textEditStockLevelQty = QtWidgets.QTextEdit(self.frame_5)
        self.textEditStockLevelQty.setGeometry(QtCore.QRect(150, 432, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditStockLevelQty.setFont(font)
        self.textEditStockLevelQty.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditStockLevelQty.setObjectName("textEditStockLevelQty")
        self.label_67 = QtWidgets.QLabel(self.frame_5)
        self.label_67.setGeometry(QtCore.QRect(30, 435, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.textEditOnHandQty = QtWidgets.QTextEdit(self.frame_5)
        self.textEditOnHandQty.setGeometry(QtCore.QRect(150, 464, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditOnHandQty.setFont(font)
        self.textEditOnHandQty.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditOnHandQty.setObjectName("textEditOnHandQty")
        self.label_68 = QtWidgets.QLabel(self.frame_5)
        self.label_68.setGeometry(QtCore.QRect(30, 468, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.checkBoxIsInventory = QtWidgets.QCheckBox(self.frame_5)
        self.checkBoxIsInventory.setGeometry(QtCore.QRect(150, 500, 70, 17))
        self.checkBoxIsInventory.setText("")
        self.checkBoxIsInventory.setObjectName("checkBoxIsInventory")
        self.label_69 = QtWidgets.QLabel(self.frame_5)
        self.label_69.setGeometry(QtCore.QRect(30, 497, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.textEditRemarks = QtWidgets.QTextEdit(self.frame_5)
        self.textEditRemarks.setGeometry(QtCore.QRect(720, 70, 401, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditRemarks.setFont(font)
        self.textEditRemarks.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditRemarks.setObjectName("textEditRemarks")
        self.label_70 = QtWidgets.QLabel(self.frame_5)
        self.label_70.setGeometry(QtCore.QRect(600, 77, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.textEditGenericName = QtWidgets.QTextEdit(self.frame_5)
        self.textEditGenericName.setGeometry(QtCore.QRect(720, 4, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditGenericName.setFont(font)
        self.textEditGenericName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditGenericName.setObjectName("textEditGenericName")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(600, 7, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(600, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBoxVAT = QtWidgets.QComboBox(self.frame_5)
        self.comboBoxVAT.setGeometry(QtCore.QRect(720, 36, 181, 31))
        self.comboBoxVAT.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxVAT.setObjectName("comboBoxVAT")
        self.label_71 = QtWidgets.QLabel(self.frame_5)
        self.label_71.setGeometry(QtCore.QRect(600, 206, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.checkBoxIsPackaged = QtWidgets.QCheckBox(self.frame_5)
        self.checkBoxIsPackaged.setGeometry(QtCore.QRect(720, 208, 70, 17))
        self.checkBoxIsPackaged.setText("")
        self.checkBoxIsPackaged.setObjectName("checkBoxIsPackaged")
        self.dateEditExpiryDate = QtWidgets.QDateEdit(self.frame_5)
        self.dateEditExpiryDate.setGeometry(QtCore.QRect(720, 225, 101, 31))
        self.dateEditExpiryDate.setCalendarPopup(True)  # Show calendar when clicked          
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.dateEditExpiryDate.setFont(font)
        self.dateEditExpiryDate.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_72 = QtWidgets.QLabel(self.frame_5)
        self.label_72.setGeometry(QtCore.QRect(600, 230, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.textEditLotNo = QtWidgets.QTextEdit(self.frame_5)
        self.textEditLotNo.setGeometry(QtCore.QRect(720, 257, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditLotNo.setFont(font)
        self.textEditLotNo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditLotNo.setObjectName("textEditLotNo")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(600, 260, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(600, 293, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEditConversionValue = QtWidgets.QTextEdit(self.frame_5)
        self.textEditConversionValue.setGeometry(QtCore.QRect(720, 290, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditConversionValue.setFont(font)
        self.textEditConversionValue.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEditConversionValue.setObjectName("textEditConversionValue")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(600, 327, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBoxChildItem = QtWidgets.QComboBox(self.frame_5)
        self.comboBoxChildItem.setGeometry(QtCore.QRect(720, 322, 401, 31))
        self.comboBoxChildItem.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBoxChildItem.setObjectName("comboBoxChildItem")
        self.label_73 = QtWidgets.QLabel(self.frame_5)
        self.label_73.setGeometry(QtCore.QRect(600, 358, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.checkBoxIsMonitored = QtWidgets.QCheckBox(self.frame_5)
        self.checkBoxIsMonitored.setGeometry(QtCore.QRect(720, 360, 70, 17))
        self.checkBoxIsMonitored.setText("")
        self.checkBoxIsMonitored.setObjectName("checkBoxIsMonitored")
        self.pushButtonUploadImage = QtWidgets.QPushButton(self.frame_5)
        self.pushButtonUploadImage.setGeometry(QtCore.QRect(600, 380, 81, 31))
        self.pushButtonUploadImage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonUploadImage.setObjectName("pushButtonUploadImage")
        self.textEditImageFilePath = QtWidgets.QTextEdit(self.frame_5)
        self.textEditImageFilePath.setGeometry(QtCore.QRect(720, 380, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditImageFilePath.setFont(font)
        self.textEditImageFilePath.setStyleSheet("background-color: rgb(226, 226, 226);\n"
"color: rgb(0, 0, 0);")
        self.textEditImageFilePath.setReadOnly(True)
        self.textEditImageFilePath.setObjectName("textEditImageFilePath")
        self.label_74 = QtWidgets.QLabel(self.frame_5)
        self.label_74.setGeometry(QtCore.QRect(600, 420, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.checkBoxIsStickerPrinted = QtWidgets.QCheckBox(self.frame_5)
        self.checkBoxIsStickerPrinted.setGeometry(QtCore.QRect(720, 420, 70, 17))
        self.checkBoxIsStickerPrinted.setText("")
        self.checkBoxIsStickerPrinted.setObjectName("checkBoxIsStickerPrinted")
        self.tabWidget.addTab(self.tabGeneralInformation, "")
        self.tabItemPriceList = QtWidgets.QWidget()
        self.tabItemPriceList.setObjectName("tabItemPriceList")
        self.frame_21 = QtWidgets.QFrame(self.tabItemPriceList)
        self.frame_21.setGeometry(QtCore.QRect(0, 0, 1361, 651))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.tableWidgetItemPrice = QtWidgets.QTableWidget(self.frame_21)
        self.tableWidgetItemPrice.setGeometry(QtCore.QRect(0, 50, 1361, 601))
        self.tableWidgetItemPrice.setMinimumSize(QtCore.QSize(1361, 0))
        self.tableWidgetItemPrice.setObjectName("tableWidgetItemPrice")
        self.tableWidgetItemPrice.setColumnCount(5)
        self.tableWidgetItemPrice.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPrice.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPrice.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPrice.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPrice.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPrice.setHorizontalHeaderItem(4, item)
        self.pushButtonAddItemPrice = QtWidgets.QPushButton(self.frame_21)
        self.pushButtonAddItemPrice.setGeometry(QtCore.QRect(1280, 5, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddItemPrice.setFont(font)
        self.pushButtonAddItemPrice.setAutoFillBackground(False)
        self.pushButtonAddItemPrice.setStyleSheet("background-color: rgb(1, 166, 240);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonAddItemPrice.setObjectName("pushButtonAddItemPrice")
        self.frame_22 = QtWidgets.QFrame(self.tabItemPriceList)
        self.frame_22.setGeometry(QtCore.QRect(0, 650, 1371, 37))
        self.frame_22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.pushButtonItemPriceFirst = QtWidgets.QPushButton(self.frame_22)
        self.pushButtonItemPriceFirst.setGeometry(QtCore.QRect(10, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemPriceFirst.setFont(font)
        self.pushButtonItemPriceFirst.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemPriceFirst.setFlat(True)
        self.pushButtonItemPriceFirst.setObjectName("pushButtonItemPriceFirst")
        self.pushButtonItemPricePrevious = QtWidgets.QPushButton(self.frame_22)
        self.pushButtonItemPricePrevious.setGeometry(QtCore.QRect(90, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemPricePrevious.setFont(font)
        self.pushButtonItemPricePrevious.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemPricePrevious.setFlat(True)
        self.pushButtonItemPricePrevious.setObjectName("pushButtonItemPricePrevious")
        self.pushButtonItemPriceNext = QtWidgets.QPushButton(self.frame_22)
        self.pushButtonItemPriceNext.setGeometry(QtCore.QRect(230, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemPriceNext.setFont(font)
        self.pushButtonItemPriceNext.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemPriceNext.setFlat(True)
        self.pushButtonItemPriceNext.setObjectName("pushButtonItemPriceNext")
        self.pushButtonItemPriceLast = QtWidgets.QPushButton(self.frame_22)
        self.pushButtonItemPriceLast.setGeometry(QtCore.QRect(310, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemPriceLast.setFont(font)
        self.pushButtonItemPriceLast.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemPriceLast.setFlat(True)
        self.pushButtonItemPriceLast.setObjectName("pushButtonItemPriceLast")
        self.textEditPageItemPriceNumber = QtWidgets.QTextEdit(self.frame_22)
        self.textEditPageItemPriceNumber.setGeometry(QtCore.QRect(170, 3, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditPageItemPriceNumber.setFont(font)
        self.textEditPageItemPriceNumber.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEditPageItemPriceNumber.setReadOnly(True)
        self.textEditPageItemPriceNumber.setObjectName("textEditPageItemPriceNumber")
        self.tabWidget.addTab(self.tabItemPriceList, "")
        self.tabItemComponentList = QtWidgets.QWidget()
        self.tabItemComponentList.setObjectName("tabItemComponentList")
        self.frame_23 = QtWidgets.QFrame(self.tabItemComponentList)
        self.frame_23.setGeometry(QtCore.QRect(0, 0, 1361, 651))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.tableWidgetItemComponent = QtWidgets.QTableWidget(self.frame_23)
        self.tableWidgetItemComponent.setGeometry(QtCore.QRect(0, 50, 1361, 601))
        self.tableWidgetItemComponent.setMinimumSize(QtCore.QSize(1361, 0))
        self.tableWidgetItemComponent.setObjectName("tableWidgetItemComponent")
        self.tableWidgetItemComponent.setColumnCount(8)
        self.tableWidgetItemComponent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemComponent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemComponent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemComponent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemComponent.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemComponent.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemComponent.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemComponent.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemComponent.setHorizontalHeaderItem(7, item)
        self.pushButtonAddItemComponent = QtWidgets.QPushButton(self.frame_23)
        self.pushButtonAddItemComponent.setGeometry(QtCore.QRect(1280, 5, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddItemComponent.setFont(font)
        self.pushButtonAddItemComponent.setAutoFillBackground(False)
        self.pushButtonAddItemComponent.setStyleSheet("background-color: rgb(1, 166, 240);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonAddItemComponent.setObjectName("pushButtonAddItemComponent")
        self.frame_24 = QtWidgets.QFrame(self.tabItemComponentList)
        self.frame_24.setGeometry(QtCore.QRect(0, 650, 1371, 37))
        self.frame_24.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.pushButtonItemComponentFirst = QtWidgets.QPushButton(self.frame_24)
        self.pushButtonItemComponentFirst.setGeometry(QtCore.QRect(10, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemComponentFirst.setFont(font)
        self.pushButtonItemComponentFirst.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemComponentFirst.setFlat(True)
        self.pushButtonItemComponentFirst.setObjectName("pushButtonItemComponentFirst")
        self.pushButtonItemComponentPrevious = QtWidgets.QPushButton(self.frame_24)
        self.pushButtonItemComponentPrevious.setGeometry(QtCore.QRect(90, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemComponentPrevious.setFont(font)
        self.pushButtonItemComponentPrevious.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemComponentPrevious.setFlat(True)
        self.pushButtonItemComponentPrevious.setObjectName("pushButtonItemComponentPrevious")
        self.pushButtonItemComponentNext = QtWidgets.QPushButton(self.frame_24)
        self.pushButtonItemComponentNext.setGeometry(QtCore.QRect(230, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemComponentNext.setFont(font)
        self.pushButtonItemComponentNext.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemComponentNext.setFlat(True)
        self.pushButtonItemComponentNext.setObjectName("pushButtonItemComponentNext")
        self.pushButtonItemComponentLast = QtWidgets.QPushButton(self.frame_24)
        self.pushButtonItemComponentLast.setGeometry(QtCore.QRect(310, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemComponentLast.setFont(font)
        self.pushButtonItemComponentLast.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemComponentLast.setFlat(True)
        self.pushButtonItemComponentLast.setObjectName("pushButtonItemComponentLast")
        self.textEditPageItemComponentNumber = QtWidgets.QTextEdit(self.frame_24)
        self.textEditPageItemComponentNumber.setGeometry(QtCore.QRect(170, 3, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditPageItemComponentNumber.setFont(font)
        self.textEditPageItemComponentNumber.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEditPageItemComponentNumber.setReadOnly(True)
        self.textEditPageItemComponentNumber.setObjectName("textEditPageItemComponentNumber")
        self.tabWidget.addTab(self.tabItemComponentList, "")
        self.tabItemPackageList = QtWidgets.QWidget()
        self.tabItemPackageList.setObjectName("tabItemPackageList")
        self.frame_25 = QtWidgets.QFrame(self.tabItemPackageList)
        self.frame_25.setGeometry(QtCore.QRect(0, 650, 1371, 37))
        self.frame_25.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.pushButtonItemPackageFirst = QtWidgets.QPushButton(self.frame_25)
        self.pushButtonItemPackageFirst.setGeometry(QtCore.QRect(10, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemPackageFirst.setFont(font)
        self.pushButtonItemPackageFirst.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemPackageFirst.setFlat(True)
        self.pushButtonItemPackageFirst.setObjectName("pushButtonItemPackageFirst")
        self.pushButtonItemPackagePrevious = QtWidgets.QPushButton(self.frame_25)
        self.pushButtonItemPackagePrevious.setGeometry(QtCore.QRect(90, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemPackagePrevious.setFont(font)
        self.pushButtonItemPackagePrevious.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemPackagePrevious.setFlat(True)
        self.pushButtonItemPackagePrevious.setObjectName("pushButtonItemPackagePrevious")
        self.pushButtonItemPackageNext = QtWidgets.QPushButton(self.frame_25)
        self.pushButtonItemPackageNext.setGeometry(QtCore.QRect(230, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemPackageNext.setFont(font)
        self.pushButtonItemPackageNext.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemPackageNext.setFlat(True)
        self.pushButtonItemPackageNext.setObjectName("pushButtonItemPackageNext")
        self.pushButtonItemPackageLast = QtWidgets.QPushButton(self.frame_25)
        self.pushButtonItemPackageLast.setGeometry(QtCore.QRect(310, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemPackageLast.setFont(font)
        self.pushButtonItemPackageLast.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemPackageLast.setFlat(True)
        self.pushButtonItemPackageLast.setObjectName("pushButtonItemPackageLast")
        self.textEditPageItemPackageNumber = QtWidgets.QTextEdit(self.frame_25)
        self.textEditPageItemPackageNumber.setGeometry(QtCore.QRect(170, 3, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditPageItemPackageNumber.setFont(font)
        self.textEditPageItemPackageNumber.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEditPageItemPackageNumber.setReadOnly(True)
        self.textEditPageItemPackageNumber.setObjectName("textEditPageItemPackageNumber")
        self.frame_26 = QtWidgets.QFrame(self.tabItemPackageList)
        self.frame_26.setGeometry(QtCore.QRect(0, 0, 1361, 651))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.tableWidgetItemPackage = QtWidgets.QTableWidget(self.frame_26)
        self.tableWidgetItemPackage.setGeometry(QtCore.QRect(0, 50, 1361, 601))
        self.tableWidgetItemPackage.setMinimumSize(QtCore.QSize(1361, 0))
        self.tableWidgetItemPackage.setObjectName("tableWidgetItemPackage")
        self.tableWidgetItemPackage.setColumnCount(6)
        self.tableWidgetItemPackage.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPackage.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPackage.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPackage.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPackage.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPackage.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemPackage.setHorizontalHeaderItem(5, item)
        self.pushButtonAddItemPackage = QtWidgets.QPushButton(self.frame_26)
        self.pushButtonAddItemPackage.setGeometry(QtCore.QRect(1280, 5, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddItemPackage.setFont(font)
        self.pushButtonAddItemPackage.setAutoFillBackground(False)
        self.pushButtonAddItemPackage.setStyleSheet("background-color: rgb(1, 166, 240);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonAddItemPackage.setObjectName("pushButtonAddItemPackage")
        self.tabWidget.addTab(self.tabItemPackageList, "")
        self.tabItemAddOnsList = QtWidgets.QWidget()
        self.tabItemAddOnsList.setObjectName("tabItemAddOnsList")
        self.frame_27 = QtWidgets.QFrame(self.tabItemAddOnsList)
        self.frame_27.setGeometry(QtCore.QRect(0, 0, 1361, 651))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.tableWidgetItemAddOns = QtWidgets.QTableWidget(self.frame_27)
        self.tableWidgetItemAddOns.setGeometry(QtCore.QRect(0, 50, 1361, 601))
        self.tableWidgetItemAddOns.setMinimumSize(QtCore.QSize(1361, 0))
        self.tableWidgetItemAddOns.setObjectName("tableWidgetItemAddOns")
        self.tableWidgetItemAddOns.setColumnCount(3)
        self.tableWidgetItemAddOns.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemAddOns.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemAddOns.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemAddOns.setHorizontalHeaderItem(2, item)
        self.pushButtonAddItemAddOns = QtWidgets.QPushButton(self.frame_27)
        self.pushButtonAddItemAddOns.setGeometry(QtCore.QRect(1280, 5, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddItemAddOns.setFont(font)
        self.pushButtonAddItemAddOns.setAutoFillBackground(False)
        self.pushButtonAddItemAddOns.setStyleSheet("background-color: rgb(1, 166, 240);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonAddItemAddOns.setObjectName("pushButtonAddItemAddOns")
        self.frame_28 = QtWidgets.QFrame(self.tabItemAddOnsList)
        self.frame_28.setGeometry(QtCore.QRect(0, 650, 1371, 37))
        self.frame_28.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.pushButtonItemAddOnsFirst = QtWidgets.QPushButton(self.frame_28)
        self.pushButtonItemAddOnsFirst.setGeometry(QtCore.QRect(10, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemAddOnsFirst.setFont(font)
        self.pushButtonItemAddOnsFirst.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemAddOnsFirst.setFlat(True)
        self.pushButtonItemAddOnsFirst.setObjectName("pushButtonItemAddOnsFirst")
        self.pushButtonItemAddOnsPrevious = QtWidgets.QPushButton(self.frame_28)
        self.pushButtonItemAddOnsPrevious.setGeometry(QtCore.QRect(90, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemAddOnsPrevious.setFont(font)
        self.pushButtonItemAddOnsPrevious.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemAddOnsPrevious.setFlat(True)
        self.pushButtonItemAddOnsPrevious.setObjectName("pushButtonItemAddOnsPrevious")
        self.pushButtonItemAddOnsNext = QtWidgets.QPushButton(self.frame_28)
        self.pushButtonItemAddOnsNext.setGeometry(QtCore.QRect(230, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemAddOnsNext.setFont(font)
        self.pushButtonItemAddOnsNext.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemAddOnsNext.setFlat(True)
        self.pushButtonItemAddOnsNext.setObjectName("pushButtonItemAddOnsNext")
        self.pushButtonItemAddOnsLast = QtWidgets.QPushButton(self.frame_28)
        self.pushButtonItemAddOnsLast.setGeometry(QtCore.QRect(310, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemAddOnsLast.setFont(font)
        self.pushButtonItemAddOnsLast.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemAddOnsLast.setFlat(True)
        self.pushButtonItemAddOnsLast.setObjectName("pushButtonItemAddOnsLast")
        self.textEditPageItemAddOnsNumber = QtWidgets.QTextEdit(self.frame_28)
        self.textEditPageItemAddOnsNumber.setGeometry(QtCore.QRect(170, 3, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditPageItemAddOnsNumber.setFont(font)
        self.textEditPageItemAddOnsNumber.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEditPageItemAddOnsNumber.setReadOnly(True)
        self.textEditPageItemAddOnsNumber.setObjectName("textEditPageItemAddOnsNumber")
        self.tabWidget.addTab(self.tabItemAddOnsList, "")
        self.tabItemModifierList = QtWidgets.QWidget()
        self.tabItemModifierList.setObjectName("tabItemModifierList")
        self.frame_29 = QtWidgets.QFrame(self.tabItemModifierList)
        self.frame_29.setGeometry(QtCore.QRect(0, 650, 1371, 37))
        self.frame_29.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.pushButtonItemModifierFirst = QtWidgets.QPushButton(self.frame_29)
        self.pushButtonItemModifierFirst.setGeometry(QtCore.QRect(10, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemModifierFirst.setFont(font)
        self.pushButtonItemModifierFirst.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemModifierFirst.setFlat(True)
        self.pushButtonItemModifierFirst.setObjectName("pushButtonItemModifierFirst")
        self.pushButtonItemModifierPrevious = QtWidgets.QPushButton(self.frame_29)
        self.pushButtonItemModifierPrevious.setGeometry(QtCore.QRect(90, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemModifierPrevious.setFont(font)
        self.pushButtonItemModifierPrevious.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemModifierPrevious.setFlat(True)
        self.pushButtonItemModifierPrevious.setObjectName("pushButtonItemModifierPrevious")
        self.pushButtonItemModifierNext = QtWidgets.QPushButton(self.frame_29)
        self.pushButtonItemModifierNext.setGeometry(QtCore.QRect(230, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemModifierNext.setFont(font)
        self.pushButtonItemModifierNext.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemModifierNext.setFlat(True)
        self.pushButtonItemModifierNext.setObjectName("pushButtonItemModifierNext")
        self.pushButtonItemModifierLast = QtWidgets.QPushButton(self.frame_29)
        self.pushButtonItemModifierLast.setGeometry(QtCore.QRect(310, 0, 71, 37))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.pushButtonItemModifierLast.setFont(font)
        self.pushButtonItemModifierLast.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButtonItemModifierLast.setFlat(True)
        self.pushButtonItemModifierLast.setObjectName("pushButtonItemModifierLast")
        self.textEditPageItemModifierNumber = QtWidgets.QTextEdit(self.frame_29)
        self.textEditPageItemModifierNumber.setGeometry(QtCore.QRect(170, 3, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.textEditPageItemModifierNumber.setFont(font)
        self.textEditPageItemModifierNumber.setStyleSheet("color: rgb(0, 0, 0);")
        self.textEditPageItemModifierNumber.setReadOnly(True)
        self.textEditPageItemModifierNumber.setObjectName("textEditPageItemModifierNumber")
        self.frame_30 = QtWidgets.QFrame(self.tabItemModifierList)
        self.frame_30.setGeometry(QtCore.QRect(0, 0, 1361, 651))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.tableWidgetItemModifier = QtWidgets.QTableWidget(self.frame_30)
        self.tableWidgetItemModifier.setGeometry(QtCore.QRect(0, 50, 1361, 601))
        self.tableWidgetItemModifier.setMinimumSize(QtCore.QSize(1361, 0))
        self.tableWidgetItemModifier.setObjectName("tableWidgetItemModifier")
        self.tableWidgetItemModifier.setColumnCount(3)
        self.tableWidgetItemModifier.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemModifier.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemModifier.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetItemModifier.setHorizontalHeaderItem(2, item)
        self.pushButtonAddItemModifier = QtWidgets.QPushButton(self.frame_30)
        self.pushButtonAddItemModifier.setGeometry(QtCore.QRect(1280, 5, 70, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddItemModifier.setFont(font)
        self.pushButtonAddItemModifier.setAutoFillBackground(False)
        self.pushButtonAddItemModifier.setStyleSheet("background-color: rgb(1, 166, 240);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonAddItemModifier.setObjectName("pushButtonAddItemModifier")
        self.tabWidget.addTab(self.tabItemModifierList, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Item Detail"))
        self.pushButtonClose.setText(_translate("Form", "Close"))
        self.pushButtonUnlock.setText(_translate("Form", "Unlock"))
        self.pushButtonLock.setText(_translate("Form", "Lock"))
        self.label_3.setText(_translate("Form", "Item Code:"))
        self.label_4.setText(_translate("Form", "Barcode (SKU):"))
        self.label_53.setText(_translate("Form", "Item Description:"))
        self.label_54.setText(_translate("Form", "Alias:"))
        self.label_55.setText(_translate("Form", "Category:"))
        self.label_62.setText(_translate("Form", "Unit:"))
        self.label_63.setText(_translate("Form", "Default Supplier:"))
        self.label_64.setText(_translate("Form", "Cost:"))
        self.label_65.setText(_translate("Form", "Mark Up (%):"))
        self.label_66.setText(_translate("Form", "Price:"))
        self.label_67.setText(_translate("Form", "Stock Level Qty:"))
        self.label_68.setText(_translate("Form", "On-hand Qty:"))
        self.label_69.setText(_translate("Form", "Is Inventoriable:"))
        self.label_70.setText(_translate("Form", "Remarks:"))
        self.label_5.setText(_translate("Form", "Generic Name:"))
        self.label_6.setText(_translate("Form", "Sales VAT:"))
        self.label_71.setText(_translate("Form", "Is Packaged:"))
        self.label_72.setText(_translate("Form", "Expiry Date:"))
        self.label_7.setText(_translate("Form", "Lot No.:"))
        self.label_8.setText(_translate("Form", "Conversion Value:"))
        self.label_9.setText(_translate("Form", "Child Item:"))
        self.label_73.setText(_translate("Form", "Is Monitored:"))
        self.pushButtonUploadImage.setText(_translate("Form", "Upload Image"))
        self.label_74.setText(_translate("Form", "Is Sticker Printed:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneralInformation), _translate("Form", "General Information"))
        item = self.tableWidgetItemPrice.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Price Description"))
        item = self.tableWidgetItemPrice.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Price"))
        item = self.tableWidgetItemPrice.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Trigger Quantity"))
        self.pushButtonAddItemPrice.setText(_translate("Form", "Add"))
        self.pushButtonItemPriceFirst.setText(_translate("Form", "First"))
        self.pushButtonItemPricePrevious.setText(_translate("Form", "Previous"))
        self.pushButtonItemPriceNext.setText(_translate("Form", "Next"))
        self.pushButtonItemPriceLast.setText(_translate("Form", "Last"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabItemPriceList), _translate("Form", "Item Price List"))
        item = self.tableWidgetItemComponent.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Item Description"))
        item = self.tableWidgetItemComponent.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Unit"))
        item = self.tableWidgetItemComponent.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Qty."))
        item = self.tableWidgetItemComponent.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Cost"))
        item = self.tableWidgetItemComponent.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Amount"))
        item = self.tableWidgetItemComponent.horizontalHeaderItem(7)
        item.setText(_translate("Form", "On-hand Qty."))
        self.pushButtonAddItemComponent.setText(_translate("Form", "Add"))
        self.pushButtonItemComponentFirst.setText(_translate("Form", "First"))
        self.pushButtonItemComponentPrevious.setText(_translate("Form", "Previous"))
        self.pushButtonItemComponentNext.setText(_translate("Form", "Next"))
        self.pushButtonItemComponentLast.setText(_translate("Form", "Last"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabItemComponentList), _translate("Form", "Item Component List"))
        self.pushButtonItemPackageFirst.setText(_translate("Form", "First"))
        self.pushButtonItemPackagePrevious.setText(_translate("Form", "Previous"))
        self.pushButtonItemPackageNext.setText(_translate("Form", "Next"))
        self.pushButtonItemPackageLast.setText(_translate("Form", "Last"))
        item = self.tableWidgetItemPackage.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Item Description"))
        item = self.tableWidgetItemPackage.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Unit"))
        item = self.tableWidgetItemPackage.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Qty."))
        item = self.tableWidgetItemPackage.horizontalHeaderItem(5)
        item.setText(_translate("Form", "O"))
        self.pushButtonAddItemPackage.setText(_translate("Form", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabItemPackageList), _translate("Form", "Item Package List"))
        item = self.tableWidgetItemAddOns.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Item Description"))
        self.pushButtonAddItemAddOns.setText(_translate("Form", "Add"))
        self.pushButtonItemAddOnsFirst.setText(_translate("Form", "First"))
        self.pushButtonItemAddOnsPrevious.setText(_translate("Form", "Previous"))
        self.pushButtonItemAddOnsNext.setText(_translate("Form", "Next"))
        self.pushButtonItemAddOnsLast.setText(_translate("Form", "Last"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabItemAddOnsList), _translate("Form", "Item Add-ons List"))
        self.pushButtonItemModifierFirst.setText(_translate("Form", "First"))
        self.pushButtonItemModifierPrevious.setText(_translate("Form", "Previous"))
        self.pushButtonItemModifierNext.setText(_translate("Form", "Next"))
        self.pushButtonItemModifierLast.setText(_translate("Form", "Last"))
        item = self.tableWidgetItemModifier.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Item Description"))
        self.pushButtonAddItemModifier.setText(_translate("Form", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabItemModifierList), _translate("Form", "Item Modifier List"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
